### ISSUE TITLE
Package dependencies not specified in DESCRIPTION

### ISSUE THREAD

**Issue by carljv** [jthomasmock/tidytuesdaymeta#2]
Hi — the package was failing to install and it looks like the problem is the dependencies aren't specified in the DESCRIPTION file. Based on the NAMESPACE file, it looks like you might need something like:
```
Imports: 
  dplyr,
  glue,
  fs,
  here,
  knitr,
  lubridate,
  rtweet
  tibble,
  whisker
Remotes:
  hadley/emo
```

**Comment by jthomasmock** [comment]
Hey Carl, I'll work on adding those, but this package likely isn't ready for lots of external use. Still very tailored to my own workspace to make generating content easier.

Ellis and I are going to try to move user-facing functions to tidytuesdayR  

https://github.com/thebioengineer/tidytuesdayR

**Comment by carljv** [comment]
Sure. I'm just posting because a colleague of mine was trying to do some work from the 
rfordatascience/tidytuesday repo, and it seems to be calling this package, which she couldn't install. See the script here, e.g.:

https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-02-11/readme.md

It sounds like maybe their repo shouldn't be relying on this package.

Thanks!

**Comment by jthomasmock** [comment]
Ahh! Thanks for letting me know, yah I should not have included that. It's not quite ready for public use yet. 

I'll adjust the cleaning script to remove that package and function call. Thanks again!
